// Code generated by mockery 2.12.1. DO NOT EDIT.

package kubernetes_mocks

import (
	mock "github.com/stretchr/testify/mock"
	rest "k8s.io/client-go/rest"

	testing "testing"

	v1beta1 "k8s.io/client-go/kubernetes/typed/authorization/v1beta1"
)

// AuthorizationV1beta1Interface is an autogenerated mock type for the AuthorizationV1beta1Interface type
type AuthorizationV1beta1Interface struct {
	mock.Mock
}

// LocalSubjectAccessReviews provides a mock function with given fields: namespace
func (_m *AuthorizationV1beta1Interface) LocalSubjectAccessReviews(namespace string) v1beta1.LocalSubjectAccessReviewInterface {
	ret := _m.Called(namespace)

	var r0 v1beta1.LocalSubjectAccessReviewInterface
	if rf, ok := ret.Get(0).(func(string) v1beta1.LocalSubjectAccessReviewInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.LocalSubjectAccessReviewInterface)
		}
	}

	return r0
}

// RESTClient provides a mock function with given fields:
func (_m *AuthorizationV1beta1Interface) RESTClient() rest.Interface {
	ret := _m.Called()

	var r0 rest.Interface
	if rf, ok := ret.Get(0).(func() rest.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.Interface)
		}
	}

	return r0
}

// SelfSubjectAccessReviews provides a mock function with given fields:
func (_m *AuthorizationV1beta1Interface) SelfSubjectAccessReviews() v1beta1.SelfSubjectAccessReviewInterface {
	ret := _m.Called()

	var r0 v1beta1.SelfSubjectAccessReviewInterface
	if rf, ok := ret.Get(0).(func() v1beta1.SelfSubjectAccessReviewInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.SelfSubjectAccessReviewInterface)
		}
	}

	return r0
}

// SelfSubjectRulesReviews provides a mock function with given fields:
func (_m *AuthorizationV1beta1Interface) SelfSubjectRulesReviews() v1beta1.SelfSubjectRulesReviewInterface {
	ret := _m.Called()

	var r0 v1beta1.SelfSubjectRulesReviewInterface
	if rf, ok := ret.Get(0).(func() v1beta1.SelfSubjectRulesReviewInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.SelfSubjectRulesReviewInterface)
		}
	}

	return r0
}

// SubjectAccessReviews provides a mock function with given fields:
func (_m *AuthorizationV1beta1Interface) SubjectAccessReviews() v1beta1.SubjectAccessReviewInterface {
	ret := _m.Called()

	var r0 v1beta1.SubjectAccessReviewInterface
	if rf, ok := ret.Get(0).(func() v1beta1.SubjectAccessReviewInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.SubjectAccessReviewInterface)
		}
	}

	return r0
}

// NewAuthorizationV1beta1Interface creates a new instance of AuthorizationV1beta1Interface. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthorizationV1beta1Interface(t testing.TB) *AuthorizationV1beta1Interface {
	mock := &AuthorizationV1beta1Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
