apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "akash-node.fullname" . }}
  labels:
    app: {{ template "akash-node.name" . }}
    chart: {{ template "akash-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - backend:
              serviceName: {{ template "akash-node.fullname" . }}
              servicePort: akashd-rpc
    - host: api.akashtest.net
      http:
        paths:
          - backend:
              serviceName: {{ template "akash-node.fullname" . }}
              servicePort: akashd-rpc
