apiVersion: v1
kind: Service
metadata:
  name: {{ template "akash-node.fullname" . }}
  labels:
    app: {{ template "akash-node.name" . }}
    chart: {{ template "akash-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.akashd.ports.p2p }}
      name: akashd-p2p
    - port: {{ .Values.akashd.ports.rpc }}
      name: akashd-rpc
  selector:
    app: {{ template "akash-node.name" . }}
    release: {{ .Release.Name }}
