apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "akash-node.fullname" . }}
  labels:
    app: {{ template "akash-node.name" . }}
    chart: {{ template "akash-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    akash.network/component: akashd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: "128Gi"
