// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	context "context"

	manifest "github.com/ovrclk/akash/manifest"
	mock "github.com/stretchr/testify/mock"

	types "github.com/ovrclk/akash/x/deployment/types"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Submit provides a mock function with given fields: _a0, _a1, _a2
func (_m *Client) Submit(_a0 context.Context, _a1 types.DeploymentID, _a2 manifest.Manifest) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.DeploymentID, manifest.Manifest) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
