---
version: "2"
issues:
  max-issues-per-linter: 1000
  max-same-issues: 1000
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - cyclop
    - errcheck
    - errchkjson
    - errorlint
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nilnil
    - noctx
    # - nolintlint # very good linter, but there are 109 issues to solve
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: comment on exported (method|function|type|const|var)
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    errorlint:
      errorf: false
    cyclop:
      max-complexity: 40
    gocritic:
      disabled-checks:
        - ifElseChain
        - singleCaseSwitch
        - commentFormatting
    revive:
      rules:
        - name: context-as-argument
        - name: error-return
        - name: error-naming
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
