linters:
  enable-all: true

# all available settings of specific linters
linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true

issues:
  exclude:
    - comment on exported (method|function|type|const|var)
  exclude-use-default: true

# Skip generated k8s code
skip-dirs:
  - pkg/client/clientset

# Skip vendor/ etc
skip-dirs-use-default: true
