issues:
  exclude:
    - comment on exported (method|function|type|const|var)
  exclude-use-default: true

# Skip generated k8s code
run:
  skip-dirs:
    - pkg/client
    - ".*/mocks"

  # Skip vendor/ etc
  skip-dirs-use-default: true
