---
version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - errchkjson
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - unparam
    - unused
settings:
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
exclusions:
  generated: lax
  presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
  rules:
    - path: (.+)\.go$
      text: comment on exported (method|function|type|const|var)
  paths:
    - third_party$
    - builtin$
    - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
