# See documentation at http://goreleaser.com
builds:
  - id: akash
    binary: akash
    main: ./cmd/akash
    goarch: [amd64, arm64]
    goos: [linux, darwin]
    ignore:
      - goos: darwin
        goarch: 386
    ldflags: -s -w -X github.com/ovrclk/akash/version.version={{.Version}} -X github.com/ovrclk/akash/version.commit={{.Commit}} -X github.com/ovrclk/akash/version.date={{.Date}}

  - id: akashd
    binary: akashd
    main: ./cmd/akashd
    goarch: [amd64, arm64]
    goos: [linux,darwin]
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
    ldflags: -s -w -X github.com/ovrclk/akash/version.version={{.Version}} -X github.com/ovrclk/akash/version.commit={{.Commit}} -X github.com/ovrclk/akash/version.date={{.Date}}

archives:
  - id: akash
    builds:
    - akash
    - akashd
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: zip
    files:
      - none*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

dockers:
  - binaries: 
    - akash
    dockerfile: _build/Dockerfile.akash
    goos: linux
    goarch: amd64
    image_templates:  
    - "ovrclk/akash:latest"
    - "ovrclk/akash:{{ .ShortCommit }}"
    - "ovrclk/akash:{{ .Version }}"
    - "ovrclk/akash:v{{ .Major }}"
    - "ovrclk/akash:v{{ .Major }}.{{ .Minor }}"

  - binaries: 
    - akashd
    dockerfile: _build/Dockerfile.akashd
    goos: linux
    goarch: amd64
    image_templates:  
    - "ovrclk/akashd:latest"
    - "ovrclk/akashd:{{ .ShortCommit }}"
    - "ovrclk/akashd:{{ .Version }}"
    - "ovrclk/akashd:v{{ .Major }}"
    - "ovrclk/akashd:v{{ .Major }}{{ .Minor }}"

brews:
  - name: akash
    ids:
    - akash
    - akashd
    github:
      owner: ovrclk
      name: homebrew-tap
    homepage: "https://akash.network"
    description: "Blockchain-powered decentralized compute platform"
    install: |
      bin.install "akash"
      bin.install "akashd"

release:
  github:
    owner: ovrclk
    name: akash
  prerelease: auto
  draft: false
