---
version: 2
project_name: node
dist: ./.cache/goreleaser/main
env:
  - GO111MODULE=on
  - CGO_ENABLED=1
builds:
  - id: akash-darwin-amd64
    binary: akash
    main: ./cmd/akash
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - CC=o64-clang
      - CXX=o64-clang++
      - CGO_CFLAGS=-mmacosx-version-min=10.12
      - CGO_LDFLAGS=-L./.cache/lib -mmacosx-version-min=10.12
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }} static_wasm"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_LDFLAGS }}"
      - -s -w
      - -linkmode=external
  - id: akash-darwin-arm64
    binary: akash
    main: ./cmd/akash
    goarch:
      - arm64
    goos:
      - darwin
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
      - CGO_CFLAGS=-mmacosx-version-min=10.12
      - CGO_LDFLAGS=-L./.cache/lib -mmacosx-version-min=10.12
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }} static_wasm"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_LDFLAGS }}"
      - -s -w
      - -linkmode=external
  - id: akash-linux-amd64
    binary: akash
    main: ./cmd/akash
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_LDFLAGS }}"
      - -s -w
      - -linkmode=external
      - -extldflags "-L./.cache/lib -lwasmvm_muslc.x86_64 -Wl,-z,muldefs -lm -lrt -lc -static"
  - id: akash-linux-arm64
    binary: akash
    main: ./cmd/akash
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_LDFLAGS }}"
      - -s -w
      - -linkmode=external
      - -extldflags "-L./.cache/lib -lwasmvm_muslc.aarch64 -Wl,-z,muldefs -lm -lrt -lc -static"
universal_binaries:
  - id: akash-darwin-universal
    ids:
      - akash-darwin-amd64
      - akash-darwin-arm64
    replace: true
    name_template: "akash"
archives:
  - id: w/version
    ids:
      - akash-darwin-universal
      - akash-linux-amd64
      - akash-linux-arm64
    name_template: "akash_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    formats:
      - zip
    files:
      - none*
  - id: wo/version
    ids:
      - akash-darwin-universal
      - akash-linux-amd64
      - akash-linux-arm64
    name_template: "akash_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    formats:
      - zip
    files:
      - none*

checksum:
  # You can change the name of the checksums file.
  # Default is `{{ .ProjectName }}_{{ .Version }}_checksums.txt`.
  name_template: "akash_{{ .Version }}_checksums.txt"

dockers:
  - dockerfile: _build/akash.Dockerfile
    use: buildx
    goarch: amd64
    goos: linux
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url={{ .GitURL }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.version={{ replace .Version "+" "-" }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
    image_templates:
      - '{{ .Env.DOCKER_IMAGE }}:{{ .ShortCommit }}-amd64'
      - '{{ .Env.DOCKER_IMAGE }}:{{ replace .Version "+" "-" }}-amd64'
      - '{{ .Env.DOCKER_IMAGE }}:{{if eq .Env.STABLE "true"}}stable{{else}}latest{{end}}-amd64'
  - dockerfile: _build/akash.Dockerfile
    use: buildx
    goarch: arm64
    goos: linux
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url={{ .GitURL }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.version={{ replace .Version "+" "-" }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
    image_templates:
      - '{{ .Env.DOCKER_IMAGE }}:{{ .ShortCommit }}-arm64'
      - '{{ .Env.DOCKER_IMAGE }}:{{ replace .Version "+" "-" }}-arm64'
      - '{{ .Env.DOCKER_IMAGE }}:{{if eq .Env.STABLE "true"}}stable{{else}}latest{{end}}-arm64'
docker_manifests:
  - name_template: "{{ .Env.DOCKER_IMAGE }}:{{ .ShortCommit }}"
    image_templates:
      - '{{ .Env.DOCKER_IMAGE }}:{{ .ShortCommit }}-amd64'
      - '{{ .Env.DOCKER_IMAGE }}:{{ .ShortCommit }}-arm64'
  - name_template: '{{ .Env.DOCKER_IMAGE }}:{{ replace .Version "+" "-" }}'
    image_templates:
      - '{{ .Env.DOCKER_IMAGE }}:{{ replace .Version "+" "-" }}-amd64'
      - '{{ .Env.DOCKER_IMAGE }}:{{ replace .Version "+" "-" }}-arm64'
  - name_template: "{{ .Env.DOCKER_IMAGE }}:latest"
    image_templates:
      - "{{ .Env.DOCKER_IMAGE }}:latest-amd64"
      - "{{ .Env.DOCKER_IMAGE }}:latest-arm64"

nfpms:
  - id: w/version
    vendor: "Akash Network"
    homepage: "https://akash.network"
    maintainer: "Akash Network <hello@akash.network>"
    file_name_template: "akash_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - deb
      - rpm
    license: Apache 2.0
  - id: wo/version
    vendor: "Akash Network"
    homepage: "https://akash.network"
    maintainer: "Akash Network <hello@akash.network>"
    file_name_template: "akash_{{ .Os }}_{{ .Arch }}"
    formats:
      - deb
      - rpm
    license: Apache 2.0

release:
  github:
    owner: akash-network
    name: node
  prerelease: auto
  mode: replace
  draft: false
