# See documentation at http://goreleaser.com
builds:
  - id: akashctl
    binary: akashctl
    main: ./cmd/akashctl
    goarch: [amd64, arm64]
    goos: [linux, darwin]
    ignore:
      - goos: darwin
        goarch: 386
    ldflags: >
      -s -w 
      -X github.com/cosmos/cosmos-sdk/version.Name=akashctl 
      -X github.com/cosmos/cosmos-sdk/version.ServerName=akashd 
      -X github.com/cosmos/cosmos-sdk/version.ClientName=akashctl 
      -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger
      -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} 
      -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} 
  - id: akashd
    binary: akashd
    main: ./cmd/akashd
    goarch: [amd64, arm64]
    goos: [linux,darwin]
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
    ldflags: >
      -s -w 
      -X github.com/cosmos/cosmos-sdk/version.Name=akashctl 
      -X github.com/cosmos/cosmos-sdk/version.ServerName=akashd 
      -X github.com/cosmos/cosmos-sdk/version.ClientName=akashctl 
      -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger
      -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} 
      -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} 

archives:
  - id: akash
    builds:
    - akashctl
    - akashd
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: zip
    files:
      - none*

dockers:
  - binaries: 
    - akashctl
    dockerfile: _build/Dockerfile.akash
    goos: linux
    goarch: amd64
    image_templates:  
    - "ovrclk/akashctl:latest"
    - "ovrclk/akashctl:{{ .ShortCommit }}"
    - "ovrclk/akashctl:{{ .Version }}"

  - binaries: 
    - akashd
    dockerfile: _build/Dockerfile.akashd
    goos: linux
    goarch: amd64
    image_templates:  
    - "ovrclk/akashd:latest"
    - "ovrclk/akashd:{{ .ShortCommit }}"
    - "ovrclk/akashd:{{ .Version }}"

brews:
  - name: akash
    github:
      owner: ovrclk
      name: homebrew-tap
    homepage: "https://akash.network"
    description: "Blockchain-powered decentralized compute platform"
    install: |
      bin.install "akashctl"
      bin.install "akashd"

nfpms:
  - 
    vendor: Overclock Labs Inc.
    homepage: http://ovrclk.com
    maintainer: Greg Osuri <greg@akash.network>
    formats:
      - deb
      - rpm
    license: Apache 2.0

release:
  github:
    owner: ovrclk
    name: akash
  prerelease: auto
  draft: false
