env:
  - GO111MODULE=on
  - CGO_ENABLED=1
builds:
  - id: akash-linux-amd64
    binary: akash
    main: ./cmd/akash
    goarch:
      - amd64
    goos:
      - linux
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    flags:
      - "-mod={{ .Env.MOD }}"
      - "-tags={{ .Env.BUILD_TAGS }}"
      - -trimpath
    ldflags:
      - "{{ .Env.BUILD_VARS }}"
      - "{{ .Env.STRIP_FLAGS }}"
      - "-linkmode={{ .Env.LINKMODE }}"
      - -extldflags "-lc -lrt -lpthread --static"
dockers:
  - ids:
      - akash-linux-amd64
    dockerfile: _build/Dockerfile.akash
    goos: linux
    goarch: amd64
    image_templates:
      - 'ghcr.io/ovrclk/akash:latest'

archives:
  - format: binary
