# See documentation at http://goreleaser.com
builds:
  - id: akash
    binary: akash
    main: ./cmd/akash
    goarch: [amd64, arm64]
    goos: [linux, darwin]
    ignore:
      - goos: darwin
        goarch: 386
    flags:
      - -tags={{if eq .Env.MAINNET "true"}}mainnet{{else}}testnet{{end}}
    ldflags: >
      -s -w 
      -X github.com/cosmos/cosmos-sdk/version.Name=akash 
      -X github.com/cosmos/cosmos-sdk/version.AppName=akash
      -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger
      -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} 
      -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} 

archives:
  - id: akash
    builds:
    - akash
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: zip
    files:
      - none*

dockers:
  - binaries:
    - akash
    dockerfile: _build/Dockerfile.akash
    goos: linux
    goarch: amd64
    image_templates:
    - "ovrclk/akash:{{if eq .Env.MAINNET "true"}}stable{{else}}latest{{end}}"
    - "ovrclk/akash:{{ .ShortCommit }}"
    - "ovrclk/akash:{{ .Version }}"

brews:
  - name: akash
    github:
      owner: ovrclk
      name: homebrew-tap
    homepage: "https://akash.network"
    description: "Blockchain-powered decentralized compute platform"
    install: |
      bin.install "akash"

nfpms:
  - 
    vendor: Overclock Labs Inc.
    homepage: http://ovrclk.com
    maintainer: Greg Osuri <greg@akash.network>
    formats:
      - deb
      - rpm
    license: Apache 2.0

release:
  github:
    owner: ovrclk
    name: akash
  prerelease: auto
  draft: false
