dir: mocks
structname: '{{.InterfaceName}}'
filename: "{{.StructName}}_mock.go"
template: testify
template-data:
  unroll-variadic: true
packages:
  pkg.akt.dev/node/v2/testutil/cosmos:
    config:
      dir: testutil/cosmos/mocks
    interfaces:
      AuthzKeeper: {}
      AccountKeeper: {}
      BankKeeper: {}
      TakeKeeper: {}
