ignore:
  - "**/*.pb.go"
  - "**/mocks/.*"
  - "pkg"
comment:
  layout: " diff, flags, files"
  behavior: once
  require_changes: true  # if true: only post the comment if coverage changes
  require_base: yes      # [yes :: must have a base report to post]
  require_head: yes      # [yes :: must have a head report to post]
  branches:              # branch names that can post comment
    - "master"
codecov:
  require_ci_to_pass: true
parsers:
  gcov:
    branch_detection:
      loop: true
      macro: false
      method: false
      conditional: true
coverage:
  range: 70..100
  round: down
  precision: 2
