---
version: "2.0"
services:
  web:
    image: quay.io/ovrclk/demo-app
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 2379
        to:
          - global: true
      - port: 2379
        to:
          - global: true
        proto: udp
profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 64Mi
        storage:
          size: 128Mi
  placement:
    westcoast:
      attributes:
        region: us-west
      pricing:
        web: 
          denom:  uakt 
          amount: 10000
deployment:
  web:
    westcoast:
      profile: web
      count: 1
