bases:
  - github.com/ovrclk/akash/_docs/kustomize/akash-provider?ref=master
  # local location: - ../../kustomize/akash-provider

namespace: akash-services

images:
  - name: ovrclk/akash
    ##
    # akash version
    ##
    newTag: 0.9.0-rc3

configMapGenerator:

  ##
  # cosmos-sdk client (config.toml) options
  ##
  - name: akash-client-config
    behavior: merge
    ##
    # place overrides in client-config.txt
    #
    # node=tcp://akashd:26657
    # chain-id=local
    ##
    env: client-config.txt

  ##
  # Akash provider service option overrides
  ##
  - name: akash-provider-config
    behavior: merge
    literals:
      - cluster-node-port-quantity=100
      - bid-price-strategy=randomRange
    ##
    # place overrides in provider-config.txt
    #
    # ingress-static-hosts=false
    # ingress-domain=app.localhost
    ##
    env: provider-config.txt

patchesJson6902:

  ##
  #  Configure gateway host in `gateway-host.yaml`.  Its value
  #  should be the hostname from the on-chain Provider.HostURI
  #  field.
  ##

  - path: gateway-host.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: akash-provider

secretGenerator:

  ##
  # Account key material
  ##

  - name: akash-provider-keys
    behavior: replace
    files:
      - key.txt
      - key-pass.txt
