// Code generated by mockery v1.0.0. DO NOT EDIT.

package kubernetes_mocks

import mock "github.com/stretchr/testify/mock"

// NetworkPolicyExpansion is an autogenerated mock type for the NetworkPolicyExpansion type
type NetworkPolicyExpansion struct {
	mock.Mock
}
