apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: photond1
  labels:
    app: photond1
spec:
  type: NodePort
  ports:
  - port: 46656
    name: photond1-p2p
  - port: 46657
    name: photond1-rpc
  - port: 46658
    name: photond1-proxyapp
  selector:
    app: photond1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: photond1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: photond1
    spec:
      containers:
      - name: photond1
        image: quay.io/ovrclk/photon:demo
        imagePullPolicy: Always
        command: ["./_demo/run.sh"]
        args: ["photond1"]
        ports:
        - containerPort: 46656
        - containerPort: 46657
        - containerPort: 46658
        volumeMounts:
          - name: photond1
            mountPath: /go/src/github.com/ovrclk/photon/static_data/photond1
      volumes:
        - name: photond1
          configMap:
            name: photond1
      imagePullSecrets:
      - name: ovrclk-builder-pull-secret
