apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: akash-ip-operator-manage-service
subjects:
  - kind: ServiceAccount
    name: akash-ip-operator
    namespace: akash-services
roleRef:
  kind: ClusterRole
  name: akash-ip-op-manage-service
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: akash-ip-operator-watch-providerleasedip
subjects:
  - kind: ServiceAccount
    name: akash-ip-operator
    namespace: akash-services
roleRef:
  kind: ClusterRole
  name: akash-ip-op-watch-providerleasedip
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: akash-ip-operator-watch-configmaps
subjects:
  - kind: ServiceAccount
    name: akash-ip-operator
    namespace: akash-services
roleRef:
  kind: ClusterRole
  name: akash-ip-op-watch-configmaps
  apiGroup: rbac.authorization.k8s.io

