// Code generated by mockery 2.12.1. DO NOT EDIT.

package kubernetes_mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"

	v1beta1 "k8s.io/client-go/kubernetes/typed/policy/v1beta1"
)

// EvictionsGetter is an autogenerated mock type for the EvictionsGetter type
type EvictionsGetter struct {
	mock.Mock
}

// Evictions provides a mock function with given fields: namespace
func (_m *EvictionsGetter) Evictions(namespace string) v1beta1.EvictionInterface {
	ret := _m.Called(namespace)

	var r0 v1beta1.EvictionInterface
	if rf, ok := ret.Get(0).(func(string) v1beta1.EvictionInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.EvictionInterface)
		}
	}

	return r0
}

// NewEvictionsGetter creates a new instance of EvictionsGetter. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewEvictionsGetter(t testing.TB) *EvictionsGetter {
	mock := &EvictionsGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
