apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: akashd
spec:
  rules:
    - host: akashd.localhost
      http:
        paths:
          - backend: 
              serviceName: akashd
              servicePort: akashd-rpc
