apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: akash
spec:
  rules:
    - host: akash.localhost
      http:
        paths:
          - backend: 
              serviceName: akash
              servicePort: akash-rpc
