---
version: "1.5"

include:
  - "foo.yaml"
  - "https://foo.yaml"

services:

  db-master:
    image: postgres
    expose:
      - port: 5432
        proto: tcp
        to:
          - service: db-pool
          - service: db-pool
            global:  true
          - service: db-slave
            global: true

  db-slave:
    image: postgres-slave
    depends-on:
      - service: db-master
    expose:
      - port: 5432
        proto: tcp
        to:
          - service: db-pool

  db-pool:
    image: db-pool
    depends-on:
      - service: db-slave
      - service: db-master
    expose:
      - port: 5432
        proto: tcp
        to:
          - service: web

  web:
    image: foo:latest
    env:
      - "API_KEY=996fb92427ae41e4649b934ca495991b785"
    port: 80
    depends-on:
      - service: db-pool
    expose:
      - port: 443
        as: 8080
        accept:
          - foo.com
        to:
          - global: true

profiles:

  compute:
    web:
      cpu: "0.01"
      memory: "128Mi"
      storage: "512Mi"
    db:
      cpu: "0.01"
      memory: "128Mi"
      storage: "1Gi"
    db-pool:
      cpu: "0.01"
      memory: "128Mi"
      storage: "512Mi"

  placement:
    westcoast:
      attributes:
        region: us-west
      pricing:
        web: 10u
        db:  50u
        db-pool:
          denom: akash
          amount: 30
    eastcoast:
      attributes:
        region: us-east
      pricing:
        web:
          denom: akash
          amount: 30
        db:
          denom: akash
          amount: 60
        db-pool:
          denom: akash
          amount: 40

deployment:

  db-master:
    westcoast:
      profile: db
      count: 1

  db-slave:
    westcoast:
      profile: db
      count: 1
    eastcoast:
      profile: db
      count: 1

  db-pool:
    westcoast:
      profile: db-pool
      count: 1
    eastcoast:
      profile: db-pool
      count: 1

  web:
    westcoast:
      profile: web
      count: 2
    eastcoast:
      profile: web
      count: 2
