// Code generated by mockery 2.12.1. DO NOT EDIT.

package kubernetes_mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"

	v1alpha1 "k8s.io/client-go/kubernetes/typed/rbac/v1alpha1"
)

// ClusterRolesGetter is an autogenerated mock type for the ClusterRolesGetter type
type ClusterRolesGetter struct {
	mock.Mock
}

// ClusterRoles provides a mock function with given fields:
func (_m *ClusterRolesGetter) ClusterRoles() v1alpha1.ClusterRoleInterface {
	ret := _m.Called()

	var r0 v1alpha1.ClusterRoleInterface
	if rf, ok := ret.Get(0).(func() v1alpha1.ClusterRoleInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1alpha1.ClusterRoleInterface)
		}
	}

	return r0
}

// NewClusterRolesGetter creates a new instance of ClusterRolesGetter. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewClusterRolesGetter(t testing.TB) *ClusterRolesGetter {
	mock := &ClusterRolesGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
