// Code generated by mockery v1.1.2. DO NOT EDIT.

package kubernetes_mocks

import mock "github.com/stretchr/testify/mock"

// RoleBindingExpansion is an autogenerated mock type for the RoleBindingExpansion type
type RoleBindingExpansion struct {
	mock.Mock
}
