apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "akash-provider.fullname" . }}
  labels:
    app: {{ template "akash-provider.name" . }}
    chart: {{ template "akash-provider.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "akash-provider.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "akash-provider.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/sh" , "/config/run.sh" ]
          env:
            - name: AKASH_NODE
              value: http://node-0-akash-node:46657
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: {{ template "akash-provider.fullname" . }}
