// Code generated by mockery v1.0.0. DO NOT EDIT.

package kubernetes_mocks

import mock "github.com/stretchr/testify/mock"

// PodTemplateExpansion is an autogenerated mock type for the PodTemplateExpansion type
type PodTemplateExpansion struct {
	mock.Mock
}
