// Code generated by mockery 2.12.1. DO NOT EDIT.

package kubernetes_mocks

import (
	context "context"

	autoscalingv1 "k8s.io/api/autoscaling/v1"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	mock "github.com/stretchr/testify/mock"

	testing "testing"

	types "k8s.io/apimachinery/pkg/types"

	v1 "k8s.io/client-go/applyconfigurations/autoscaling/v1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// HorizontalPodAutoscalerInterface is an autogenerated mock type for the HorizontalPodAutoscalerInterface type
type HorizontalPodAutoscalerInterface struct {
	mock.Mock
}

// Apply provides a mock function with given fields: ctx, horizontalPodAutoscaler, opts
func (_m *HorizontalPodAutoscalerInterface) Apply(ctx context.Context, horizontalPodAutoscaler *v1.HorizontalPodAutoscalerApplyConfiguration, opts metav1.ApplyOptions) (*autoscalingv1.HorizontalPodAutoscaler, error) {
	ret := _m.Called(ctx, horizontalPodAutoscaler, opts)

	var r0 *autoscalingv1.HorizontalPodAutoscaler
	if rf, ok := ret.Get(0).(func(context.Context, *v1.HorizontalPodAutoscalerApplyConfiguration, metav1.ApplyOptions) *autoscalingv1.HorizontalPodAutoscaler); ok {
		r0 = rf(ctx, horizontalPodAutoscaler, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*autoscalingv1.HorizontalPodAutoscaler)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1.HorizontalPodAutoscalerApplyConfiguration, metav1.ApplyOptions) error); ok {
		r1 = rf(ctx, horizontalPodAutoscaler, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApplyStatus provides a mock function with given fields: ctx, horizontalPodAutoscaler, opts
func (_m *HorizontalPodAutoscalerInterface) ApplyStatus(ctx context.Context, horizontalPodAutoscaler *v1.HorizontalPodAutoscalerApplyConfiguration, opts metav1.ApplyOptions) (*autoscalingv1.HorizontalPodAutoscaler, error) {
	ret := _m.Called(ctx, horizontalPodAutoscaler, opts)

	var r0 *autoscalingv1.HorizontalPodAutoscaler
	if rf, ok := ret.Get(0).(func(context.Context, *v1.HorizontalPodAutoscalerApplyConfiguration, metav1.ApplyOptions) *autoscalingv1.HorizontalPodAutoscaler); ok {
		r0 = rf(ctx, horizontalPodAutoscaler, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*autoscalingv1.HorizontalPodAutoscaler)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1.HorizontalPodAutoscalerApplyConfiguration, metav1.ApplyOptions) error); ok {
		r1 = rf(ctx, horizontalPodAutoscaler, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, horizontalPodAutoscaler, opts
func (_m *HorizontalPodAutoscalerInterface) Create(ctx context.Context, horizontalPodAutoscaler *autoscalingv1.HorizontalPodAutoscaler, opts metav1.CreateOptions) (*autoscalingv1.HorizontalPodAutoscaler, error) {
	ret := _m.Called(ctx, horizontalPodAutoscaler, opts)

	var r0 *autoscalingv1.HorizontalPodAutoscaler
	if rf, ok := ret.Get(0).(func(context.Context, *autoscalingv1.HorizontalPodAutoscaler, metav1.CreateOptions) *autoscalingv1.HorizontalPodAutoscaler); ok {
		r0 = rf(ctx, horizontalPodAutoscaler, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*autoscalingv1.HorizontalPodAutoscaler)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *autoscalingv1.HorizontalPodAutoscaler, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, horizontalPodAutoscaler, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *HorizontalPodAutoscalerInterface) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCollection provides a mock function with given fields: ctx, opts, listOpts
func (_m *HorizontalPodAutoscalerInterface) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	ret := _m.Called(ctx, opts, listOpts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error); ok {
		r0 = rf(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *HorizontalPodAutoscalerInterface) Get(ctx context.Context, name string, opts metav1.GetOptions) (*autoscalingv1.HorizontalPodAutoscaler, error) {
	ret := _m.Called(ctx, name, opts)

	var r0 *autoscalingv1.HorizontalPodAutoscaler
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) *autoscalingv1.HorizontalPodAutoscaler); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*autoscalingv1.HorizontalPodAutoscaler)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, metav1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, opts
func (_m *HorizontalPodAutoscalerInterface) List(ctx context.Context, opts metav1.ListOptions) (*autoscalingv1.HorizontalPodAutoscalerList, error) {
	ret := _m.Called(ctx, opts)

	var r0 *autoscalingv1.HorizontalPodAutoscalerList
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) *autoscalingv1.HorizontalPodAutoscalerList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*autoscalingv1.HorizontalPodAutoscalerList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Patch provides a mock function with given fields: ctx, name, pt, data, opts, subresources
func (_m *HorizontalPodAutoscalerInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*autoscalingv1.HorizontalPodAutoscaler, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, pt, data, opts)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *autoscalingv1.HorizontalPodAutoscaler
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) *autoscalingv1.HorizontalPodAutoscaler); ok {
		r0 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*autoscalingv1.HorizontalPodAutoscaler)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) error); ok {
		r1 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, horizontalPodAutoscaler, opts
func (_m *HorizontalPodAutoscalerInterface) Update(ctx context.Context, horizontalPodAutoscaler *autoscalingv1.HorizontalPodAutoscaler, opts metav1.UpdateOptions) (*autoscalingv1.HorizontalPodAutoscaler, error) {
	ret := _m.Called(ctx, horizontalPodAutoscaler, opts)

	var r0 *autoscalingv1.HorizontalPodAutoscaler
	if rf, ok := ret.Get(0).(func(context.Context, *autoscalingv1.HorizontalPodAutoscaler, metav1.UpdateOptions) *autoscalingv1.HorizontalPodAutoscaler); ok {
		r0 = rf(ctx, horizontalPodAutoscaler, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*autoscalingv1.HorizontalPodAutoscaler)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *autoscalingv1.HorizontalPodAutoscaler, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, horizontalPodAutoscaler, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, horizontalPodAutoscaler, opts
func (_m *HorizontalPodAutoscalerInterface) UpdateStatus(ctx context.Context, horizontalPodAutoscaler *autoscalingv1.HorizontalPodAutoscaler, opts metav1.UpdateOptions) (*autoscalingv1.HorizontalPodAutoscaler, error) {
	ret := _m.Called(ctx, horizontalPodAutoscaler, opts)

	var r0 *autoscalingv1.HorizontalPodAutoscaler
	if rf, ok := ret.Get(0).(func(context.Context, *autoscalingv1.HorizontalPodAutoscaler, metav1.UpdateOptions) *autoscalingv1.HorizontalPodAutoscaler); ok {
		r0 = rf(ctx, horizontalPodAutoscaler, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*autoscalingv1.HorizontalPodAutoscaler)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *autoscalingv1.HorizontalPodAutoscaler, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, horizontalPodAutoscaler, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *HorizontalPodAutoscalerInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	var r0 watch.Interface
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHorizontalPodAutoscalerInterface creates a new instance of HorizontalPodAutoscalerInterface. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewHorizontalPodAutoscalerInterface(t testing.TB) *HorizontalPodAutoscalerInterface {
	mock := &HorizontalPodAutoscalerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
