// Code generated by mockery v1.0.0. DO NOT EDIT.

package kubernetes_mocks

import mock "github.com/stretchr/testify/mock"

// FlowSchemaExpansion is an autogenerated mock type for the FlowSchemaExpansion type
type FlowSchemaExpansion struct {
	mock.Mock
}
