// Code generated by mockery 2.12.1. DO NOT EDIT.

package kubernetes_mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// LocalSubjectAccessReviewExpansion is an autogenerated mock type for the LocalSubjectAccessReviewExpansion type
type LocalSubjectAccessReviewExpansion struct {
	mock.Mock
}

// NewLocalSubjectAccessReviewExpansion creates a new instance of LocalSubjectAccessReviewExpansion. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewLocalSubjectAccessReviewExpansion(t testing.TB) *LocalSubjectAccessReviewExpansion {
	mock := &LocalSubjectAccessReviewExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
