// Code generated by mockery v1.1.2. DO NOT EDIT.

package kubernetes_mocks

import mock "github.com/stretchr/testify/mock"

// SelfSubjectRulesReviewExpansion is an autogenerated mock type for the SelfSubjectRulesReviewExpansion type
type SelfSubjectRulesReviewExpansion struct {
	mock.Mock
}
