// Code generated by mockery 2.12.1. DO NOT EDIT.

package kubernetes_mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/client-go/kubernetes/typed/authorization/v1"
)

// SubjectAccessReviewsGetter is an autogenerated mock type for the SubjectAccessReviewsGetter type
type SubjectAccessReviewsGetter struct {
	mock.Mock
}

// SubjectAccessReviews provides a mock function with given fields:
func (_m *SubjectAccessReviewsGetter) SubjectAccessReviews() v1.SubjectAccessReviewInterface {
	ret := _m.Called()

	var r0 v1.SubjectAccessReviewInterface
	if rf, ok := ret.Get(0).(func() v1.SubjectAccessReviewInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.SubjectAccessReviewInterface)
		}
	}

	return r0
}

// NewSubjectAccessReviewsGetter creates a new instance of SubjectAccessReviewsGetter. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewSubjectAccessReviewsGetter(t testing.TB) *SubjectAccessReviewsGetter {
	mock := &SubjectAccessReviewsGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
