// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: akash/market/v1beta1/params.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	BidMinDeposit types.Coin `protobuf:"bytes,1,opt,name=bid_min_deposit,json=bidMinDeposit,proto3" json:"bid_min_deposit" yaml:"bid_min_deposit"`
	OrderMaxBids  uint32     `protobuf:"varint,2,opt,name=order_max_bids,json=orderMaxBids,proto3" json:"order_max_bids" yaml:"order_max_bids"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d76da213caa5dbb, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBidMinDeposit() types.Coin {
	if m != nil {
		return m.BidMinDeposit
	}
	return types.Coin{}
}

func (m *Params) GetOrderMaxBids() uint32 {
	if m != nil {
		return m.OrderMaxBids
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "akash.market.v1beta1.Params")
}

func init() { proto.RegisterFile("akash/market/v1beta1/params.proto", fileDescriptor_7d76da213caa5dbb) }

var fileDescriptor_7d76da213caa5dbb = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x31, 0x4f, 0x32, 0x31,
	0x18, 0xc7, 0xaf, 0xef, 0xc0, 0x70, 0x2f, 0x68, 0x42, 0xd0, 0x20, 0x43, 0x8b, 0x37, 0x18, 0xa6,
	0x36, 0xe8, 0xa6, 0x8b, 0x39, 0x5d, 0x89, 0x86, 0xd1, 0xe5, 0xd2, 0xde, 0x5d, 0xa0, 0x81, 0xde,
	0x73, 0xb9, 0x56, 0x02, 0x1f, 0xc0, 0xdd, 0x8f, 0xc5, 0xc8, 0xe8, 0xd4, 0x98, 0x63, 0x63, 0xc4,
	0x2f, 0x60, 0xb8, 0x8a, 0x41, 0xb6, 0xa6, 0xff, 0xdf, 0xff, 0xf7, 0x24, 0xcf, 0xe3, 0x5f, 0xf2,
	0x09, 0xd7, 0x63, 0xa6, 0x78, 0x31, 0x49, 0x0d, 0x9b, 0xf5, 0x45, 0x6a, 0x78, 0x9f, 0xe5, 0xbc,
	0xe0, 0x4a, 0xd3, 0xbc, 0x00, 0x03, 0xcd, 0x56, 0x85, 0x50, 0x87, 0xd0, 0x1f, 0xa4, 0xd3, 0x1a,
	0xc1, 0x08, 0x2a, 0x80, 0xed, 0x5e, 0x8e, 0xed, 0xe0, 0x18, 0xb4, 0x02, 0xcd, 0x04, 0xd7, 0xe9,
	0xaf, 0x2d, 0x06, 0x99, 0xb9, 0x3c, 0xf8, 0x42, 0x7e, 0xed, 0xb9, 0x92, 0x37, 0xdf, 0x90, 0x7f,
	0x2a, 0x64, 0x12, 0x29, 0x99, 0x45, 0x49, 0x9a, 0x83, 0x96, 0xa6, 0x8d, 0xba, 0xa8, 0xf7, 0xff,
	0xfa, 0x82, 0x3a, 0x0b, 0xdd, 0x59, 0xf6, 0x03, 0xe9, 0x03, 0xc8, 0x2c, 0x0c, 0x97, 0x96, 0x78,
	0xa5, 0x25, 0x8d, 0x50, 0x26, 0x03, 0x99, 0x3d, 0xba, 0xde, 0xc6, 0x92, 0x63, 0xd5, 0xd6, 0x92,
	0xf3, 0x05, 0x57, 0xd3, 0xdb, 0xe0, 0x28, 0x08, 0x86, 0x0d, 0x71, 0xd8, 0x6d, 0x72, 0xff, 0x04,
	0x8a, 0x24, 0x2d, 0x22, 0xc5, 0xe7, 0x91, 0x90, 0x89, 0x6e, 0xff, 0xeb, 0xa2, 0x5e, 0x23, 0xbc,
	0x2b, 0x2d, 0xa9, 0x3f, 0xed, 0x92, 0x01, 0x9f, 0x87, 0x32, 0xd1, 0x1b, 0x4b, 0x8e, 0xc8, 0xad,
	0x25, 0x67, 0x6e, 0xc8, 0xdf, 0xff, 0x60, 0x58, 0x87, 0x83, 0x62, 0x78, 0xbf, 0x2c, 0x31, 0x5a,
	0x95, 0x18, 0x7d, 0x96, 0x18, 0xbd, 0xaf, 0xb1, 0xb7, 0x5a, 0x63, 0xef, 0x63, 0x8d, 0xbd, 0x97,
	0xab, 0x91, 0x34, 0xe3, 0x57, 0x41, 0x63, 0x50, 0x0c, 0x66, 0x45, 0x3c, 0x9d, 0x30, 0x77, 0x90,
	0xf9, 0xfe, 0x24, 0x66, 0x91, 0xa7, 0x5a, 0xd4, 0xaa, 0xf5, 0xdd, 0x7c, 0x07, 0x00, 0x00, 0xff,
	0xff, 0xf4, 0xc5, 0xd4, 0x7a, 0xaf, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OrderMaxBids != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.OrderMaxBids))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.BidMinDeposit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.BidMinDeposit.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.OrderMaxBids != 0 {
		n += 1 + sovParams(uint64(m.OrderMaxBids))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BidMinDeposit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BidMinDeposit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderMaxBids", wireType)
			}
			m.OrderMaxBids = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrderMaxBids |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
