---
version: "1.5"

services:
  webapp:
    image: quay.io/ovrclk/demo-app
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      cpu: "100m"
      memory: "512Mi"
      storage: "512Mi"
  placement:
    san-jose:
      attributes:
        region: sjc
      pricing:
        web:
          denom: uakt
          amount: 25

deployment:
  webapp:
    san-jose:
      profile: web
      count: 1
