---
version: "2.0"
services:
  svca:
    image: nginx
    expose:
      - port: 80
        accept:
          - ahostname.com
        to:
          - global: true
      - port: 12345
        to:
          - global: true
        proto: udp
  svcb:
    image: nginx
    expose:
      - port: 80
        accept:
          - bhostname.com
        to:
          - global: true
      - port: 12346
        to:
          - global: true
        proto: udp

profiles:
  compute:
    profilea:
      resources:
        cpu:
          units: "100m"
        gpu:
          units: "1"
          attributes:
            vendor:
              nvidia:
        memory:
          size: "128Mi"
        storage:
        - size: "1Gi"
    profileb:
      resources:
        cpu:
          units: "100m"
        memory:
          size: "128Mi"
        storage:
        - size: "1Gi"
  placement:
    westcoast:
      attributes:
        region: us-west
        blalbla: foo
      signedBy:
        anyOf:
          - 1
          - 2
        allOf:
          - 3
          - 4
      pricing:
        profilea:
          denom: uakt
          amount: 50
        profileb:
          denom: uakt
          amount: 50

deployment:
  svca:
    westcoast:
      profile: profilea
      count: 1
  svcb:
    westcoast:
      profile: profileb
      count: 1
