---
version: "1.0"

services:
  web:
    image: nginx
    expose:
      - port: 80
        to:
          - global: true

profiles:

  compute:
    web:
      cpu: "100m"
      memory: "128Mi"
      disk: "1Gi"

  placement:
    westcoast:
      attributes:
        region: us-west
      pricing:
        web: 0.005000

deployment:
  web:
    westcoast:
      profile: web
      count: 2
