---
version: "2.1"
services:
 web:
   image: nginx
   expose:
     - port: 80
       accept:
         - ahostname.com
       to:
         - global: true
     - port: 12345
       to:
         - global: true
           ip: "meow"
       proto: udp
profiles:
 compute:
   web:
     resources:
       cpu:
         units: "100m"
       memory:
         size: "128Mi"
       storage:
         size: "1Gi"
 placement:
   westcoast:
     attributes:
       region: us-west
     signedBy:
       anyOf:
         - 1
         - 2
       allOf:
         - 3
         - 4
     pricing:
       web:
         denom: uakt
         amount: 50
deployment:
 web:
   westcoast:
     profile: web
     count: 2

endpoints:
  meow:
    kind: "ip"
