// Code generated by mockery 2.12.1. DO NOT EDIT.

package kubernetes_mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"

	v1beta1 "k8s.io/client-go/kubernetes/typed/apps/v1beta1"
)

// ControllerRevisionsGetter is an autogenerated mock type for the ControllerRevisionsGetter type
type ControllerRevisionsGetter struct {
	mock.Mock
}

// ControllerRevisions provides a mock function with given fields: namespace
func (_m *ControllerRevisionsGetter) ControllerRevisions(namespace string) v1beta1.ControllerRevisionInterface {
	ret := _m.Called(namespace)

	var r0 v1beta1.ControllerRevisionInterface
	if rf, ok := ret.Get(0).(func(string) v1beta1.ControllerRevisionInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1beta1.ControllerRevisionInterface)
		}
	}

	return r0
}

// NewControllerRevisionsGetter creates a new instance of ControllerRevisionsGetter. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewControllerRevisionsGetter(t testing.TB) *ControllerRevisionsGetter {
	mock := &ControllerRevisionsGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
