// Code generated by mockery v1.1.2. DO NOT EDIT.

package kubernetes_mocks

import mock "github.com/stretchr/testify/mock"

// CSIStorageCapacityExpansion is an autogenerated mock type for the CSIStorageCapacityExpansion type
type CSIStorageCapacityExpansion struct {
	mock.Mock
}
