// Code generated by mockery 2.12.1. DO NOT EDIT.

package kubernetes_mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// TokenReviewExpansion is an autogenerated mock type for the TokenReviewExpansion type
type TokenReviewExpansion struct {
	mock.Mock
}

// NewTokenReviewExpansion creates a new instance of TokenReviewExpansion. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewTokenReviewExpansion(t testing.TB) *TokenReviewExpansion {
	mock := &TokenReviewExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
