// Code generated by mockery v1.0.0. DO NOT EDIT.

package kubernetes_mocks

import mock "github.com/stretchr/testify/mock"

// ClusterRoleExpansion is an autogenerated mock type for the ClusterRoleExpansion type
type ClusterRoleExpansion struct {
	mock.Mock
}
