apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "akash-node.fullname" . }}
  labels:
    app: {{ template "akash-node.name" . }}
    chart: {{ template "akash-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  genesis.json: |-
{{ .Values.node.genesis | indent 4 }}
  priv_validator_key.json: |-
{{ .Values.node.priv_validator_key | indent 4 }}
  priv_validator_state.json: |-
{{ .Values.node.priv_validator_state | indent 4 }}
  node_key.json: |-
{{ .Values.node.node_key | indent 4 }}
  run.sh: |-
{{ .Files.Get "run.sh" | indent 4 }}
  peers.txt: |-
    {{- range $item := .Values.node.peers }}
    {{ $item.name }} {{ $item.id }}
    {{- end }}
