build :
				go build ./cmd/client
				go build ./cmd/node

client:
				go build ./cmd/client

node:
				go build ./cmd/node

clean:
				rm client
				rm node
				rm -rf $HOME/.demonode
				rm -rf $HOME/.democlient
