rbac:
  create: true

ingress:
  # Pubicly routable FQDN of the the provider, 
  #
  domain: ""

akash:
  # Address (IP/Hostname) with port of Akash node to connect to 
  #
  node: http://api.akashtest.net:80

provider:
  # Provider address. You can enerate an address by 
  # registering the provider using: `akash provider add`
  #
  address: ""

  # Host URI to advertise. Ingress domain will be 
  # used if not provided
  #
  host: {}
    # name: ""
    # ssl: false


  # Create a key using: `akash key create`
  # Defaults to release name
  #
  privateKeyName: ""

  # name of the secret storing private key,
  # defaults to <name>-private-key
  #
  privateKeySecretName: ""
  
  # port to listen on
  port: 3001

deployment:
  # ServiceType of the deployment. Some cloud providers 
  # (like aws or gcp) require either LoadBalancer / NodeHost
  #
  serviceType: ClusterIP 
  ingress:
    # enabled generation a unique url for each deployment. 
    # [uuid].domain
    #
    staticHosts: true

    # domain to map the deployed services, a wild card domain 
    # could be used -- although not mandated -- to simplify use
    # defaults to ingress.domain
    #
    domain: ""

image:
  repository: ovrclk/akash
  tag: latest
  pullPolicy: IfNotPresent
