apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "akash-provider.fullname" . }}
  labels:
    app: {{ template "akash-provider.name" . }}
    chart: {{ template "akash-provider.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - backend:
              serviceName: {{ template "akash-provider.fullname" . }}
              servicePort: http
