apiVersion: v1
kind: Service
metadata:
  name: {{ template "akash-provider.fullname" . }}
  labels:
    app: {{ template "akash-provider.name" . }}
    chart: {{ template "akash-provider.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: {{ .Values.provider.port }}
      name: http
      type: HTTP
  selector:
    app: {{ template "akash-provider.name" . }}
    release: {{ .Release.Name }}
