---
name: setup-ubuntu
runs:
  using: 'composite'
  steps:
    - name: Fetch all tags
      shell: bash
      run: |
        if git rev-parse --is-shallow-repository | grep -qxF true; then
          git fetch --prune --unshallow
        else
          git fetch --prune --tags
        fi
    - name: Install dependencies
      # Shell must explicitly specify the shell for each step. https://github.com/orgs/community/discussions/18597
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y make direnv unzip lz4 wget curl npm jq pv coreutils libudev-dev
    - name: Setup npm
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Detect required Go version
      shell: bash
      run: |
        toolchain=$(./script/tools.sh gotoolchain | sed 's/^go//')
        if [ -z "$toolchain" ]; then
            echo "Error: Failed to detect Go version from script/tools.sh" >&2
            exit 1
        fi
        echo "GOVERSION=${toolchain}" >> $GITHUB_ENV
    - uses: actions/setup-go@v5
      with:
        go-version: "${{ env.GOVERSION }}"
        check-latest: true
    - name: set environment
      uses: HatsuneMiku3939/direnv-action@v1
      with:
        masks: ''
