apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "akash-provider.fullname" . }}
  labels:
    app: {{ template "akash-provider.name" . }}
    chart: {{ template "akash-provider.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  run.sh: |-
{{ .Files.Get "run.sh" | indent 4 }}
  provider.yml: |-
    hostURI: http://{{ .Release.Name }}.{{ .Values.ingress.domain }}
    attributes:
      - name:  region
        value: {{ .Values.provider.region }}
