apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "akash-provider.fullname" . }}
  labels:
    app: {{ template "akash-provider.name" . }}
    chart: {{ template "akash-provider.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    akash.network/component: akash-provider
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: "512Mi"
