// Code generated by mockery 2.12.1. DO NOT EDIT.

package kubernetes_mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// DaemonSetExpansion is an autogenerated mock type for the DaemonSetExpansion type
type DaemonSetExpansion struct {
	mock.Mock
}

// NewDaemonSetExpansion creates a new instance of DaemonSetExpansion. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewDaemonSetExpansion(t testing.TB) *DaemonSetExpansion {
	mock := &DaemonSetExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
