// Code generated by mockery 2.12.1. DO NOT EDIT.

package kubernetes_mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// LeaseExpansion is an autogenerated mock type for the LeaseExpansion type
type LeaseExpansion struct {
	mock.Mock
}

// NewLeaseExpansion creates a new instance of LeaseExpansion. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewLeaseExpansion(t testing.TB) *LeaseExpansion {
	mock := &LeaseExpansion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
