name: integration-tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: make test-integration

