name: macos

on:
  push:
    branches: [ master ]

jobs:
  build-bins:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: make bins
      - run: make image-bins
      - run: make test
