name: macos

on:
  push:
    branches:
      - master
      - mainnet/main

env:
  MAINNET: ${{ github.ref == 'refs/heads/mainnet/main'}}

jobs:
  build-bins:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .makerc
      - uses: actions/setup-go@v2
        with:
          go-version: "^${{ env.GOLANG_VERSION }}"
      - run: make bins
      - run: make test
