name: macos

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
      - mainnet/main
  pull_request:

env:
  MAINNET: ${{ github.ref == 'refs/heads/mainnet/main'}}

jobs:
  build-bins:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - run: |
          while IFS='' read -r LINE || [ -n "${LINE}" ]; do
            echo "$LINE" >> $GITHUB_ENV;
          done < .env
      - run: |
          brew install bash
          sudo chsh -s /usr/local/bin/bash
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - run: make bins
