name: macos

on:
  push:
    branches:
      - master
      - mainnet/main

env:
  MAINNET: ${{ github.ref == 'refs/heads/mainnet/main'}}

jobs:
  build-bins:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: make bins
      - run: make docker-image
      - run: make test
