name: Protobuf

on:
  pull_request:
    paths:
      - "**.proto"
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: make proto-lint
  breakage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check-breakage
        run: make proto-check-breaking
