name: tools

on:
  push:
    branches:
      - master
      - mainnet/main
  pull_request:
    branches:
      - master
      - mainnet/main

jobs:
  shellcheck-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .env
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - run: make shellcheck
