name: shellcheck

on:
  push:
    branches:
      - master
      - mainnet/main
  pull_request:
    branches:
      - master
      - mainnet/main

jobs:
  shellcheck-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make shellcheck
