name: shellcheck

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  shellcheck-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make shellcheck
