name: Sims
on: [pull_request]
jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  test-sim-nondeterminism:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2-beta
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v1
        with:
          SUFFIX_FILTER: |
            .go
            .mod
            .sum
          SET_ENV_NAME_INSERTIONS: 1
          SET_ENV_NAME_LINES: 1
      - name: test-sim-nondeterminism
        run: |
          make test-sim-nondeterminism
        if: "env.GIT_DIFF != ''"

  test-sim-import-export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2-beta
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v1
        with:
          SUFFIX_FILTER: |
            .go
            .mod
            .sum
          SET_ENV_NAME_INSERTIONS: 1
          SET_ENV_NAME_LINES: 1
      - name: test-sim-import-export
        run: |
          make test-sim-import-export
        if: "env.GIT_DIFF != ''"

  test-sim-after-import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2-beta
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v1
        with:
          SUFFIX_FILTER: |
            .go
            .mod
            .sum
          SET_ENV_NAME_INSERTIONS: 1
          SET_ENV_NAME_LINES: 1
      - name: test-sim-after-import
        run: |
          make test-sim-after-import
        if: "env.GIT_DIFF != ''"

  test-sim-fullapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2-beta
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v1
        with:
          SUFFIX_FILTER: |
            .go
            .mod
            .sum
          SET_ENV_NAME_INSERTIONS: 1
          SET_ENV_NAME_LINES: 1
      - name: test-sim-fullapp
        run: |
          make test-sim-fullapp
        if: "env.GIT_DIFF != ''"
