name: tests
on:
  push:
    branches:
      - master
      - mainnet/main
      - develop
  pull_request:
    branches:
      - master
      - mainnet/main
      - develop

jobs:
  sim-cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  sim-nondeterminism:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .env
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - name: test-sim-nondeterminism
        run: make test-sim-nondeterminism

  sim-import-export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .env
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - name: test-sim-import-export
        run: make test-sim-import-export

  sim-after-import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .env
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - name: test-sim-after-import
        run: make test-sim-after-import

  sim-fullapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .env
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - name: test-sim-fullapp
        run: make test-sim-fullapp
